docs(messaging): add step-by-step instructions for image notification
invertase/react-native-firebase pull request #4225
Opened 2020-09-08 00:06 UTC by davidepalazzo

### Description
Based on #4218 this new piece of documentation adds a guide to setup a Notification Service Extension. 

It has screenshots to make the process a bit more visual. I wasn't too sure if you guys have a specific process for hosting images so I uploaded it on Gifyu for now. Let me know whether that needs changing or not.

Thanks!

### Related issues
#4218

### Release Summary

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
🔥

2020-09-08 13:23 UTC, Pittan commented
Thank you for creating this awesome document!  

Suggestion:  
Maybe you're missing to modify this file :pray: 
https://github.com/invertase/react-native-firebase/blob/master/docs/sidebar.yaml

2020-09-08 23:35 UTC, davidepalazzo commented
Thanks for that @Pittan, I totally missed it. Added!

2020-09-09 00:56 UTC, mikehardy commented
I had meetings all day today so couldn't make many individual contributions, hoping to review this (and merge it, I also hope) tomorrow. Thanks for putting this together @davidepalazzo

2020-09-10 19:20 UTC, mikehardy commented on docs/sidebar.yaml
> +      - '/messaging/notifications-with-image'
```suggestion
    - - Notifications with Images
      - '/messaging/notifications-with-image'
```

2020-09-10 19:22 UTC, mikehardy commented
I think the sidebar entries need a header and then the file to link, I just committed a change that should do that? We'll see when the preview is done building from the vercel bot

I asked the Invertase folks how to do images as they all seem to be hosted on prismic.io right now and I don't know how I would get images there - thanks for putting them on gifyu at least temporarily though, it helps to see them in the preview

2020-09-10 19:23 UTC, mikehardy commented
Needs attention from either @Salakar or @Ehesp to share knowledge on how to get images hosted correctly, as this new page contains Xcode explanation images

2020-09-10 19:52 UTC, mikehardy commented
Yep - sidebar is good now in the preview, just waiting on guidance for image hosting and this is good to go!

2020-09-10 22:57 UTC, davidepalazzo commented
Thanks for adding the title @mikehardy

2020-09-11 13:10 UTC, Salakar commented
We should move the images into the website directory to be sourced from there as assets (PRs welcome to set this up on the project 🤞 ). Happy for these to be on gifyu for now though (though might be good to have copies of them in an assets folder in the website directory or something for safe keeping).

Could we also change the title, description and sidebar name to be more explicit that it's for iOS - like the iOS permissions one is.

2020-09-11 14:20 UTC, mikehardy reviewed
Labelling page as iOS specific

2020-09-11 14:20 UTC, mikehardy commented on docs/messaging/notifications-with-image.md
> +title: Notifications with Image
```suggestion
title: iOS Notification Images
```

2020-09-11 14:20 UTC, mikehardy commented on docs/messaging/notifications-with-image.md
> +description: Displaying an image in a notification.
```suggestion
description: Displaying an image in an iOS notification.
```

2020-09-11 14:20 UTC, mikehardy commented on docs/sidebar.yaml
> +    - - Notifications with Images
```suggestion
    - - iOS Notification Images
```

2020-09-11 14:23 UTC, mikehardy requested changes
good feedback and sure - I just made it 'iOS Notification Images' per your request
@davidepalazzo could you make an assets directory and put the source images in there?
At that point - using the previews from Vercel that are auto-published on changes - you might be able to actually link them up directly, can you try that?

If that doesn't work we will at least have the assets for safe-keeping as requested and can figure out how to migrate all images as a separate issue to unblock this one

2020-09-12 05:18 UTC, davidepalazzo commented
@mikehardy done.

I created an `assets` folder and placed it inside a new `static` folder. The `static` directory by default gets copied into the `public` folder which is reachable from the base URL. I've done this off the top of my head based on what I remembered about [Gatsby](https://www.gatsbyjs.com/docs/static-folder/#adding-assets-outside-of-the-module-system).

Another way of doing it, would be [enabling images support in markdown using a Gatsby plugin](https://www.gatsbyjs.com/docs/working-with-images-in-markdown/#using-the-mdx-plugin). It's straight forward but maybe material for a different branch.

@Salakar if you think it could be of use in the long run then I'm happy to create a new PR when I have some time in the coming days.

I tried to add some logic to the folder structure and files naming. It mirrors the docs — this should keep things easy and organised for future contributors that want to add screengrabs.
```js
static
├── docs
│   ├── {package-name} // e.g. messaging
│   │    └─── {page-name}-{image-description} // e.g. notification-installation-screenshot.png
```

2020-09-12 06:07 UTC, mikehardy approved these changes
That looks great to me, glad you knew some gatsby off the top of your head, I never would have known how to link those up! I'll leave any plugin stuff to a separate PR I think this is good to go and helps people now

2020-09-12 06:08 UTC, merged

2020-09-12 06:09 UTC, mikehardy commented
Fantastic stuff, thank you @davidepalazzo !

2020-09-12 06:16 UTC, davidepalazzo commented
No problem @mikehardy, glad we were able to sort it out!