fix(firestore): let calls to collection on a DocumentReference take a type argument
invertase/react-native-firebase pull request #4686
Opened 2020-12-17 21:54 UTC by sanpoChew

### Description

I think this may have just been an oversight on this PR https://github.com/invertase/react-native-firebase/pull/3810

Was quite annoying having to cast types when working with subcollections so I thought I would open a PR.

### Related issues

### Release Summary

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [ ] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [ ] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

2020-12-17 21:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/invertase/react-native-firebase?pullRequest=4686) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/invertase/react-native-firebase?pullRequest=4686) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/invertase/react-native-firebase?pullRequest=4686) it.</sub>

2020-12-18 02:45 UTC, mikehardy requested changes
Hi there! Thanks for sending this in. It seems like it could work

Unfortunately, we try to maintain fidelity with the firebase-js-sdk API, and this goes a bit past it. Our current API is missing the DocumentData type on the returned CollectionReference, but simply harmonizing the API is the acceptable change here

https://github.com/firebase/firebase-js-sdk/blob/1a8cb40ac47d63105e7013a0d5ed97e12816bced/packages/firestore-types/index.d.ts#L68

2020-12-19 19:37 UTC, sanpoChew commented
not sure how useful that DocumentData addition would really be though, I suppose what I really need is https://github.com/invertase/react-native-firebase/pull/3546 if parity is what the aim is

2020-12-19 21:01 UTC, mikehardy commented
@sanpoChew I think you are right, that PR even seemed like it might work, just needs comments addressed and some cleanup. As mentioned on that PR I'd happily work with you to merge it, or if you wanted to just take this one to firebase-js-sdk parity I'll also collaborate

2020-12-28 19:06 UTC, sanpoChew commented
@mikehardy thanks for the help, I think I'll close this one for now, might have a look at the withConverter PR in the new year!

2020-12-28 19:06 UTC, closed without merging