feat(storage): Firebase JS SDK v9 modular API
invertase/react-native-firebase pull request #6958
Opened 2023-03-02 16:51 UTC by russellwheatley

### Description

See title.

### Related issues

### Release Summary

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [ ] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [ ] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

2023-03-17 11:04 UTC, Lyokone submitted a review, later dismissed

2023-03-17 22:33 UTC, mikehardy requested changes
This looks really good - I had two really minor thoughts for the changes implemented, trivial really but need a look

Main structural thought is that we've had one of these modular PRs go in with a delete of the non-modular tests, since the modular e2e *includes* the compatibility testing, that actually seems like a viable path forward, and reduces e2e time. We have also had a few go in like this where the e2e non-modular tests are effectively duplicated, with no delete of the original tests.

What do you prefer here? I lean towards a delete of the non-modular tests personally but it is a weakly held opinion.

2023-03-17 22:33 UTC, mikehardy commented on docs/database/usage/index.md
> +NOTE: To get a reference to a database other than a 'us-central1' default database, you must pass the database URL. You can find your Realtime Database URL in the Realtime Database section of the Fir
Strange, I fixed this on main already, why is this showing up in a diff here? 🤔

2023-03-17 22:33 UTC, mikehardy commented on tests/app.js
> +import * as storageModular from '@react-native-firebase/storage';
Really minor point - but can you snuggle this one up under the non-modular storage import just a few lines below? These imports have been re-positioned a couple times and right now we have it organized such that the same module is imported modular/non-modular as a unit?

2023-03-23 14:15 UTC, mikehardy approved these changes
LGTM! Thanks - another one bites the dust, and this was medium-large IMHO

2023-03-23 14:15 UTC, merged