WIP feat(oauth): added signIn and link for oauth
invertase/react-native-firebase pull request #7019
Opened 2023-04-03 15:07 UTC by Aetherall

### Description

Right now, documentation recommendation for oauth flows is to use the react-native-app-auth package.
What this package do is pretty close to the default behaviour of the firebase native sdk.

With the support of my company and of my teammates from kraaft.co, I had some time allocated to check whether I can bridge the native sdk with react native within react-native-firebase :)
 
The goals of such integration would be:
- reduce the number of dependencies of the project 
  - no need for react-native-app-auth if firebase does the same
- avoid manual fetching of the configuration needed for each provider into react-native-app-auth
  -  they are dynamic in our use case

### Related issues
https://github.com/invertase/react-native-firebase/issues/349
https://github.com/invertase/react-native-firebase/issues/3926

### Release Summary

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [ ] `iOS` -> If anyone knows his swift I'm down for some help :)
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e` -> Would like to have some insights with detox and testing the popup
  - [x] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change. // will do !
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

TO DO
---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

2023-04-07 09:16 UTC, Aetherall commented
state now is working for android, ios coming soon

2023-06-05 17:40 UTC, mikehardy commented
Sincere apologies for the delay! I'm processing the PR queue now and should have time to review this, I sincerely appreciate the effort and the patience

2023-06-22 09:02 UTC, Aetherall commented
Thank you @mikehardy, we're running this fix as a patch in production since 2 months ago, and so far its doing great

2023-06-29 21:34 UTC, mikehardy requested changes
This looks great! Happy to hear it's working for you in production that gives me a lot of confidence as I look to merge this.

I left a couple specific comments that are hopefully easy to handle

I rebased to current main and ran the linters so those hoops have already been jumped through

The only thing I can think of besides the specific comments is to add something in `docs/auth` - might make sense to great make a page there (slicing in to the prev/next links on two of the related pages to get the circular nav links going) ?

Functionally CI should go green now though 🤞  with fully up to date SDKs etc etc

2023-06-29 21:34 UTC, mikehardy commented on packages/auth/lib/index.d.ts
> +    signInWithRedirect(provider: AuthProvider): Promise<UserCredential>;
Can you document this here, even if briefly? The rnfirebase.io site is built from the typedoc so anything you put here will be seen + used

2023-06-29 21:34 UTC, mikehardy commented on packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
> +    System.out.print(exception);
Dumping an error to System.out is discouraged, if it is already being propagated up, then I think this could be removed?

2023-06-29 21:52 UTC, mikehardy commented
Looks like another of the test cases needs a modification similar to those already made:

```
  1) auth().currentUser
       linkWithPopup()
         should throw an unsupported error:
     AssertionError: expected Function { name: '' } to throw exception with a message matching 'firebase.auth.User.linkWithPopup() is unsupported by the native Firebase SDKs.', but got 'Cannot read properties of undefined (reading 'providerId')'
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (/Users/runner/work/react-native-firebase/react-native-firebase/packages/auth/e2e/user.e2e.js:880:22)
```

2023-08-18 00:00 UTC, mikehardy commented
Summer vacation time was busy enough the stale bot got this one, but it's a good looking chunk of work, hoping to get it shepherded through for merge

2024-03-25 17:21 UTC, mikehardy commented
scanning stale closed queue for unrelated reasons this still looks harvest-able

2026-08-04 15:44 UTC, russellwheatley commented
Closing this out. The native OAuth sign-in this proposed has landed on `main` through a different path: `signInWithProvider` is implemented natively on Android (`NativeRNFBTurboAuth.java`) and iOS (`RNFBAuthModule.mm`), and exposed in JS as `signInWithPopup`/`signInWithRedirect`/`linkWithPopup` (see `packages/auth/lib/index.ts` and `User.ts`), added as part of the auth TurboModules migration and the TypeScript rewrite in #8991.

Thanks for the original work here and for pushing on this for so long, sorry it didn't get shepherded through back when you were active on it.

2026-08-04 15:44 UTC, closed without merging