Android RN 72 Support - Update build.gradle w/ Namespace #224
invertase/react-native-firebase pull request #7249
Opened 2023-07-18 19:50 UTC by alexhernandez

RN Team Update:
https://github.com/react-native-community/discussions-and-proposals/issues/671

Fix:
https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1598892444

2023-07-18 19:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/invertase/react-native-firebase?pullRequest=7249) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/invertase/react-native-firebase?pullRequest=7249) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/invertase/react-native-firebase?pullRequest=7249) it.</sub>

2023-07-19 20:31 UTC, mikehardy requested changes
Oh yes! I've seen this a bit! This is also the current preferred solution I believe (it is what I've accepted in other repos I maintain anyway) - conditionally adding it to build.gradle so it is forward-compatible but *not* removing it from AndroidManifest.xml because that is sort of fiddly and makes it backwards-incompatible

Anyway - I think we have to do this in the build.gradle of every package though, not just app? That is, analytics, app-check, app-distribution, database etc etc - so there should be a large-ish batch of build.gradle diffs with the same change, one perpackage?

What do you think?

2023-09-03 21:39 UTC, mikehardy commented
This idea was taken up by @AndreiCalazans in #7323 and we've merged it and released it there. Thanks for raising this PR!

2023-09-03 21:39 UTC, closed without merging

2023-10-10 19:17 UTC, ivanignatiev commented
For RN 0.73 for

- react-native-firebase_analytics
- react-native-firebase_messaging

You also need to add `android.buildFeatures.buildConfig true` otherwise it will fail:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-firebase_analytics'.
> com.android.builder.errors.EvalIssueException: defaultConfig contains custom BuildConfig fields, but the feature is disabled.
  To enable the feature, add the following to your module-level build.gradle:
  `android.buildFeatures.buildConfig true`

BUILD FAILED in 4s
error Failed to install the app.
```