Update notifications.md
invertase/react-native-firebase pull request #7439
Opened 2023-11-06 14:36 UTC by anhtuank7c

You cannot use `useNavigation` hooks from outside of `NavigationContainer` The properly way is to implement `linking` props of `NavigationContainer`. Reference document: https://reactnavigation.org/docs/navigation-container#linkingsubscribe

### Description
The previous document was invalid for at least React Navigation v6.

### Related issues
React Navigation won't let you use `useNavigation` hooks from the outside of `NavigationContainer` scope.

### Release Summary

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [x] Yes
  - [ ] No

### Test Plan

Need a real device (for iOS) and emulator/real device for Android to test.
Use FCM to push a notification with these data: `navigationId: required` and `postId: optional`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

2023-11-06 14:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/invertase/react-native-firebase?pullRequest=7439) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/invertase/react-native-firebase?pullRequest=7439) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/invertase/react-native-firebase?pullRequest=7439) it.</sub>

2023-11-06 18:07 UTC, mikehardy requested changes
Hi there - this is no longer a minimal example, what you propose adds a screen, brings in linking and all sorts of things. The previous example was much much simpler and just showed the elements of the integration

2023-11-07 01:53 UTC, anhtuank7c commented
@mikehardy I've removed the PostScreen component to simplify the example. The linking configuration is required to make notification interaction work. Previous example doesn't work.

2023-11-27 12:53 UTC, mikehardy commented
Apologies for the delay @anhtuank7c ! Thanks for posting this. I can merge it but not without the CLA signed, can you please follow the details link (should be https://cla-assistant.io/invertase/react-native-firebase?pullRequest=7439) and sign the CLA?

Thank you!

2023-11-27 13:02 UTC, mikehardy approved these changes
OK - this looks great now - I really appreciate the contribution and hopefully it will help people

Just pending the CLA signing now - follow the details link on that CI check or in the CLA-bot notification and we should be able to get this merged after signing

Thanks!

2023-11-27 13:54 UTC, maximownrock commented on docs/messaging/notifications.md
> +  if (navigationId === 'home) {
'home'

2023-11-27 17:13 UTC, mikehardy commented on docs/messaging/notifications.md
> +  if (navigationId === 'home) {
```suggestion
  if (navigationId === 'home') {
```

2023-11-27 17:13 UTC, mikehardy approved these changes

2023-12-29 02:25 UTC, anhtuank7c commented
@mikehardy is there anything left that prevent us to merge this PR?

2024-01-06 20:15 UTC, mikehardy commented
Oh! Sorry this sat here. I think it's good to go, thank you

2024-01-06 20:15 UTC, mikehardy approved these changes

2024-01-06 20:16 UTC, merged