fix: fixed multifactor and phone auth always using default instance
invertase/react-native-firebase pull request #7564
Opened 2024-01-12 13:01 UTC by Somebodybro

### Description

The auth module had multiple places, where a fireauth instance should have been specified for proper initialization and behaviour. This pr addresses atleast those, that affect multifactor authentication.
### Related issues

[#12265](https://github.com/firebase/firebase-ios-sdk/issues/12265)
Fixes #12265
### Release Summary

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [x] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

:fire:

2024-01-12 13:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/invertase/react-native-firebase?pullRequest=7564) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/invertase/react-native-firebase?pullRequest=7564) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/invertase/react-native-firebase?pullRequest=7564) it.</sub>

2024-01-23 15:58 UTC, mikehardy commented on packages/app/package.json
> +      "firebase": "10.20.0",
reverting this change - I control the dependencies with PRs that I do on their own with testing - and I just updated this in #7585 - also it appears 10.21.0 will be the first release with the PR you really need...

```suggestion
      "firebase": "10.19.0",
```

2024-01-23 16:00 UTC, mikehardy commented on packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
> +    @ReactMethod
formatting changes shouldn't be mixed in with functional changes, and formatting should be controlled by google-java-format and our `yarn lint:android` run script should run it

```suggestion
  @ReactMethod
```

2024-01-23 16:01 UTC, mikehardy commented on packages/auth/ios/RNFBAuth/RNFBAuthModule.m
> +     [[FIRAuth authWithApp:firebaseApp]
formatting in iOS is controlled by clang-format via `yarn lint:ios:fix`

```suggestion
    [[FIRAuth authWithApp:firebaseApp]
```

2024-01-23 16:01 UTC, mikehardy commented on packages/auth/ios/RNFBAuth/RNFBAuthModule.m
> +     [[FIRAuth authWithApp:firebaseApp]
formatting in iOS is controlled by clang-format via `yarn lint:ios:fix`

```suggestion
    [[FIRAuth authWithApp:firebaseApp]
```

2024-01-23 16:02 UTC, mikehardy commented on packages/auth/ios/RNFBAuth/RNFBAuthModule.m
> +    FIRAuthStateDidChangeListenerHandle newListenerHandle =   [[FIRAuth authWithApp:firebaseApp]
formatting in iOS is controlled by clang-format via `yarn lint:ios:fix`

```suggestion
    FIRAuthStateDidChangeListenerHandle newListenerHandle = [[FIRAuth authWithApp:firebaseApp]
```

2024-01-23 16:15 UTC, mikehardy requested changes
Hey @Somebodybro 👋 - thanks for working through this both here and upstream! Well done

Upstream note: the PR you proposed to firebase-ios-sdk was merged and it was just tagged for firebase-ios-sdk 10.21.0 so hopefully that's out soon, but it is not out yet as I type this

I control the sdk versions via separate PRs, but I don't think we need to wait on this? It's still correct here I think, it just won't completely work until upstream 10.21.0 is out?

The only thing remaining here is for you to run `lint:ios:fix` and commit the results - I did that locally but I can't push the result out as your repo main branch rejects the push, so you'll have to do it yourself I think?

2024-01-25 06:02 UTC, Somebodybro commented
Hei! I ran lint:ios:fix and the repo should be linted.
Can't believe I completely forgot to do that.

Sorry I was not working on this for a couple of day. It was nice working with this library (and upstream).

2024-01-30 18:09 UTC, mikehardy approved these changes
fantastic

2024-01-30 18:10 UTC, merged