Fix Android phone sign in not returning authCredential
invertase/react-native-firebase pull request #7793
Opened 2024-05-14 22:19 UTC by joaqo

You can now upgrade anonymous users using phone auth on Android. Credit to @Shaninnik.

### Description
Issue explained here: https://github.com/invertase/react-native-firebase/issues/4911

2024-05-14 22:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/invertase/react-native-firebase?pullRequest=7793) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/invertase/react-native-firebase?pullRequest=7793) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/invertase/react-native-firebase?pullRequest=7793) it.</sub>

2024-05-14 23:10 UTC, mikehardy requested changes
Thanks for posting this - looks promising with some comments as indicated
I made them all in the form of suggestions, I'll apply them + reformat + push to the branch then do final review

I think this can go in though

2024-05-14 23:10 UTC, mikehardy commented on packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
> +  // patching anonumous phone auth linkWithCredentials
```suggestion
  // storage for anonymous phone auth credentials, used for linkWithCredentials
```

2024-05-14 23:18 UTC, mikehardy submitted a review, later dismissed
This looks reasonable, if it passes CI I can merge this in

2024-05-15 01:58 UTC, mikehardy commented
Ah, I do love a thorough test suite - it picked something up on this one so it will need some further examination before merge:

```
      linkWithCredential()
        ✔ should link anonymous account <-> email account
23:32:06.039 detox[5958] ERROR: [WS_ERROR] The app has crashed, see the details below:

@Thread pool-106-thread-1(633):
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
	at io.invertase.firebase.auth.ReactNativeFirebaseAuthModule.promiseRejectLinkAuthException(ReactNativeFirebaseAuthModule.java:2244)
	at io.invertase.firebase.auth.ReactNativeFirebaseAuthModule.lambda$linkWithCredential$34(ReactNativeFirebaseAuthModule.java:1626)
	at io.invertase.firebase.auth.ReactNativeFirebaseAuthModule.$r8$lambda$Lodml2tmhgEN3Twg2KfjZTSQTN4(Unknown Source:0)
	at io.invertase.firebase.auth.ReactNativeFirebaseAuthModule$$ExternalSyntheticLambda1.onComplete(Unknown Source:4)
	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.1.0:1)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

2024-05-15 02:57 UTC, merged

2024-05-16 21:04 UTC, joaqo commented
This is fantastic, thank you so much @mikehardy for the fixes and the merge!

2024-05-16 21:07 UTC, joaqo commented
Is there anywhere I can look to keep track for your release schedule so I know when to upgrade my dependencies? Thanks!

2024-05-22 03:39 UTC, mikehardy commented
Unfortunately our release process doesn't formally make releases in GitHub so you can't really subscribe there, apologies. I usually release things about as soon as I merge them, this one just was held up a few days on CI issues, it's out now though

2024-05-22 15:01 UTC, joaqo commented
No problem, yesterday I found you had a CHANGELOG file and noticed the new releases, so I upgraded our dependencies. Everythings working smoothly ✌️, thanks!